services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    container_name: frontend

  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile.dashboard
    ports:
      - "5174:5174"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    container_name: dashboard

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    env_file:
      - Backend/.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - backend_uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: benjaphan5
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    container_name: mongo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert/origin.pem:/etc/nginx/cert/origin.pem:ro
      - ./nginx/cert/private.key:/etc/nginx/cert/private.key:ro
    depends_on:
      - frontend
      - dashboard
      - backend
    networks:
      - app-network
    restart: unless-stopped
    container_name: nginx

volumes:
  mongo-data:
  backend_uploads:

networks:
  app-network:
    driver: bridge