services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    container_name: frontend

  dashboard:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile.dashboard
    ports:
      - "5174:5174"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    container_name: dashboard

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    env_file:
      - Backend/.env
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./Backend/uploads:/app/static-uploads
    container_name: backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: benjaphan5
    restart: unless-stopped
    container_name: mongo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/cert/origin.pem:/etc/nginx/cert/origin.pem:ro
      - ../nginx/cert/private.key:/etc/nginx/cert/private.key:ro
      - ./Backend/uploads:/app/static-uploads
    depends_on:
      - frontend
      - dashboard
      - backend
    networks:
      - app-network
    restart: unless-stopped
    container_name: nginx

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge